### ISSUE TITLE
How is your model's performance after quantization?

### ISSUE THREAD

**Issue by David-Lee-1990** [carminacodre/ModelQuantization#1]
I use the quantization method to my object detection model trained by tensorflow. 
**My system is Mac os 10.13.6 with tensorflow 1.8.**
**The speed of the original pb graph model is 18.30 FPS. And the speed of the quantization model is 18.60 FPS.** 
I only use the following function.
`transform_graph(path_to_model="models/ssd_inception_v2_coco.pb",
                save_dir="models",
                file_name ="ssd_inception_v2_coco_transformed_2.pb",
                inputs="image_tensor:0",
                outputs=['detection_boxes:0', 'detection_scores:0','detection_classes:0', 'num_detections:0'],
                transforms=optimize_quantize_weights_trans)`
 How is your model's performance? and how to make it better?

**Comment by carminacodre** [comment]
For some models I noticed an improvement, but for others not. I noticed that the speed is also dependent on the hardware architecture since I tested the transforms on different CPUs and the performance did not change in the same manner. So I cannot say that there is a general recipe.
